# Pico W digital clock + weather display on an ILI9488 480x320 SPI LCD.
#
# Weather and the local UTC offset come from Open-Meteo (free, no key, ~650
# byte responses), with OpenWeatherMap as a backup for temperatures. The old
# BOM scrapers are gone: BOM retired the pages they read in their site
# redesign, and their new JSON API is restricted to registered users.
#
# All errors are non-blocking: the clock keeps drawing, weather slots are
# blanked while their value is unavailable, and problems are shown on a tiny
# status line between the clock and the date.
#
# Wi-Fi credentials and the OpenWeatherMap API key live in settings.toml.
#
# Display driver based on:
# https://www.instructables.com/RPi-Pico-35-Inch-320x480-HVGA-TFT-LCD-ILI9488-Bitm/
# Font bitmaps + width tables are generated by tools/generate_font.py.

import gc
import ipaddress
import os
import ssl
import time

from adafruit_bus_device.spi_device import SPIDevice
import adafruit_ntp
import adafruit_requests
import board
import busio
import digitalio
from fonts import Arial14
from fonts import Roboto50
from fonts import Roboto70
from fonts import Roboto82
import rtc
import sdcardio
import socketpool
import storage
import supervisor
import wifi

# --- Configuration (from settings.toml) --------------------------------------

WIFI_SSID = os.getenv("CIRCUITPY_WIFI_SSID")
WIFI_PASSWORD = os.getenv("CIRCUITPY_WIFI_PASSWORD")

WEATHER_LATITUDE = os.getenv("WEATHER_LATITUDE") or "-37.7667"  # Brunswick VIC
WEATHER_LONGITUDE = os.getenv("WEATHER_LONGITUDE") or "144.9600"
OPEN_METEO_URL = (
    "http://api.open-meteo.com/v1/forecast"
    f"?latitude={WEATHER_LATITUDE}&longitude={WEATHER_LONGITUDE}"
    "&current=temperature_2m"
    "&daily=temperature_2m_max,temperature_2m_min,"
    "precipitation_probability_max,uv_index_max"
    "&timezone=auto&forecast_days=1"
)

OWM_API_KEY = os.getenv("OPENWEATHERMAP_API_KEY")
OWM_LOCATION = os.getenv("OPENWEATHERMAP_LOCATION") or "Melbourne,VIC,AU"
OWM_WEATHER_URL = (
    "http://api.openweathermap.org/data/2.5/weather"
    f"?q={OWM_LOCATION}&units=metric&appid={OWM_API_KEY}"
)

# Some routers hand out a DNS server that intermittently stops resolving
# ("Name or service not known"); pinning a public resolver avoids that.
# Set to "" in settings.toml to use the router's DNS instead.
STATIC_DNS = os.getenv("STATIC_DNS") or "8.8.8.8"

# Used until the first successful weather fetch reports the real offset.
UTC_OFFSET_FALLBACK = int(os.getenv("UTC_OFFSET_FALLBACK") or 36000)  # AEST

WEATHER_INTERVAL = 1 * 60 * 60
WEATHER_RETRY_INTERVAL = 5 * 60  # retry sooner when the last fetch had problems
NTP_INTERVAL = 24 * 60 * 60  # re-sync the RTC daily to correct drift

REQUEST_TIMEOUT = 10
REQUEST_RETRIES = 3

WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

# The 15px strip between the clock block (rows 0-84) and the date block
# (rows 100-184) that no other draw call touches.
STATUS_Y = 85

# (weather key, prefix glyph, suffix, x, y) for the four Roboto70 slots
WEATHER_SLOTS = (
    ("high_today", "↑", "", 0, 160),
    ("current_today", "←", "", 261, 160),
    ("chance_of_rain", "↕", "%", 0, 242),
    ("uv_index", "↔", "", 261, 242),
)
WEATHER_SLOT_WIDTH = 176

# --- Display ------------------------------------------------------------------


def rgb565(color):
    return (color[0] >> 3 << 11) + (color[1] >> 2 << 5) + (color[2] >> 3)


BLACK = rgb565((0, 0, 0))


def char_metrics(c, font):
    """Return (ord, width) for a character, falling back to the opposite case,
    then to '0' (present in every font) if the glyph is missing."""
    char_ord = ord(c)
    if char_ord in font.width:
        return char_ord, font.width[char_ord]
    swapped = ord(c.lower() if c.isupper() else c.upper())
    if swapped in font.width:
        return swapped, font.width[swapped]
    return 48, font.width[48]


def get_rendered_width(text, font):
    return sum(char_metrics(c, font)[1] for c in text)


class ILI9488:
    def __init__(self, spi, cs, rst, dc):
        self.width = 480
        self.height = 320

        self.cs = digitalio.DigitalInOut(cs)
        self.rst = digitalio.DigitalInOut(rst)
        self.rst.direction = digitalio.Direction.OUTPUT
        self.dc = digitalio.DigitalInOut(dc)
        self.dc.direction = digitalio.Direction.OUTPUT

        self.spi = SPIDevice(spi, self.cs, baudrate=60000000)

        self.buffer_size = 2048
        self.buffer = bytearray(self.buffer_size * 2)

        self.init_display()

    def init_display(self):
        self.rst.value = True
        time.sleep(0.005)
        self.rst.value = False
        time.sleep(0.01)
        self.rst.value = True
        time.sleep(0.005)

        self.write_cmd(0x21)

        self.write_cmd(0xC2)
        self.write_data(0x33)

        self.write_cmd(0xC5)
        self.write_data(0x00)
        self.write_data(0x1E)
        self.write_data(0x80)

        self.write_cmd(0xB1)
        self.write_data(0xB0)

        self.write_cmd(0xE0)
        for b in (
            0x00,
            0x13,
            0x18,
            0x04,
            0x0F,
            0x06,
            0x3A,
            0x56,
            0x4D,
            0x03,
            0x0A,
            0x06,
            0x30,
            0x3E,
            0x0F,
        ):
            self.write_data(b)

        self.write_cmd(0xE1)
        for b in (
            0x00,
            0x13,
            0x18,
            0x01,
            0x11,
            0x06,
            0x38,
            0x34,
            0x4D,
            0x06,
            0x0D,
            0x0B,
            0x31,
            0x37,
            0x0F,
        ):
            self.write_data(b)

        self.write_cmd(0x3A)
        self.write_data(0x55)

        self.write_cmd(0x11)
        time.sleep(0.12)
        self.write_cmd(0x29)

        self.write_cmd(0xB6)
        self.write_data(0x00)
        self.write_data(0x62)

        self.write_cmd(0x36)
        self.write_data(0xE8)

    def write_cmd(self, cmd):
        self.dc.value = False
        with self.spi as spi:
            if type(cmd) in (bytes, bytearray, memoryview):
                spi.write(cmd)
            else:
                spi.write(bytes([cmd]))

    def write_data(self, buf):
        self.dc.value = True
        with self.spi as spi:
            if type(buf) in (bytes, bytearray, memoryview):
                spi.write(buf)
            else:
                spi.write(bytes([buf]))

    def set_block(self, x1, y1, x2, y2):
        self.write_cmd(0x2A)
        self.write_data(x1 >> 8 & 0xFF)
        self.write_data(x1 & 0xFF)
        self.write_data(x2 - 1 >> 8 & 0xFF)
        self.write_data(x2 - 1 & 0xFF)

        self.write_cmd(0x2B)
        self.write_data(y1 >> 8 & 0xFF)
        self.write_data(y1 & 0xFF)
        self.write_data(y2 - 1 >> 8 & 0xFF)
        self.write_data(y2 - 1 & 0xFF)

        self.write_cmd(0x2C)

    def rect(self, x1, y1, x2, y2, color):
        if x2 <= x1 or y2 <= y1:
            return
        for i in range(self.buffer_size):
            self.buffer[2 * i] = color >> 8 & 0xFF
            self.buffer[2 * i + 1] = color & 0xFF
        chunks, rest = divmod((x2 - x1) * (y2 - y1), self.buffer_size)

        self.set_block(x1, y1, x2, y2)
        for _ in range(chunks):
            self.write_data(self.buffer)
        if rest != 0:
            self.write_data(memoryview(self.buffer)[: rest * 2])

    def print(self, text, old_text, x, y, width, font):
        """Draw text, redrawing only from the first character that changed."""
        cursor = x
        old_text_pad = f"{old_text[0 : len(text)]:<{len(text)}}"
        for i in range(len(text)):
            if text[i] != old_text_pad[i]:
                for j in range(i, len(text)):
                    char_ord, char_width = char_metrics(text[j], font)
                    self.set_block(
                        cursor, y, cursor + char_width, y + font.bitmap_height
                    )
                    with open(
                        f"/sd/fonts/{font.name}{font.height}/{char_ord}", "rb"
                    ) as f:
                        self.write_data(f.read())
                    cursor += char_width
                # Blank out whatever the old (possibly longer) text left behind
                self.rect(cursor, y, x + width, y + font.bitmap_height, BLACK)
                return
            cursor += char_metrics(text[i], font)[1]


# --- Drawing helpers ------------------------------------------------------------

timezone = UTC_OFFSET_FALLBACK
clock_synced = False
time_str_old = ""
date_str_old = ""
status_old = ""
weather = {key: None for key, _, _, _, _ in WEATHER_SLOTS}
weather_old = {}


def draw_clock():
    """Draw the time and date. Safe to call from anywhere, any time."""
    global time_str_old, date_str_old
    if not clock_synced:
        return
    lt = time.localtime(time.time() + timezone)

    time_str = f"{lt.tm_hour:02}:{lt.tm_min:02}:{lt.tm_sec:02}"
    lcd.print(time_str, time_str_old, 16, 0, 480, Roboto82)
    time_str_old = time_str

    date_str = f"{WEEKDAYS[lt.tm_wday]} {lt.tm_mday:02}/{lt.tm_mon:02}/{lt.tm_year}"
    date_str_width = get_rendered_width(date_str, Roboto50)
    if date_str_width > 480:  # Shorten date string if it is too long to render
        date_str = date_str[0:-4] + date_str[-2:]  # Mon 01/01/1234 -> Mon 01/01/34
        date_str_width = get_rendered_width(date_str, Roboto50)
    date_str_x_pos = max((480 - date_str_width) // 2, 0)
    lcd.print(date_str, date_str_old, date_str_x_pos, 100, 480, Roboto50)
    date_str_old = date_str


def draw_weather():
    """Draw available weather values; blank the slots of unavailable ones."""
    for key, prefix, suffix, x, y in WEATHER_SLOTS:
        val = weather[key]
        text = "" if val is None else f"{prefix}{val}{suffix}"
        old = weather_old.get(key, "")
        if text == old:
            continue
        if text:
            lcd.print(text, old, x, y, WEATHER_SLOT_WIDTH, Roboto70)
        else:
            lcd.rect(x, y, x + WEATHER_SLOT_WIDTH, y + Roboto70.bitmap_height, BLACK)
        weather_old[key] = text


def set_status(msg):
    """Show a message on the tiny status line (empty string clears it)."""
    global status_old
    if msg:
        print("status:", msg)
    if msg == status_old:
        return
    while msg and get_rendered_width(msg, Arial14) > 480:
        msg = msg[:-1]
    try:
        if msg:
            lcd.print(msg, status_old, 0, STATUS_Y, 480, Arial14)
        else:
            lcd.rect(0, STATUS_Y, 480, STATUS_Y + Arial14.bitmap_height, BLACK)
        status_old = msg
    except OSError as e:
        # Arial14 bitmaps not copied to /sd/fonts yet; serial print still works
        print("status font missing from /sd/fonts/Arial14:", e)


def ticking_sleep(seconds):
    """Sleep while keeping the clock display updating."""
    end = time.monotonic() + seconds
    while time.monotonic() < end:
        draw_clock()
        time.sleep(0.2)


# --- Networking ---------------------------------------------------------------


def connect_wifi():
    announced = False
    while not wifi.radio.connected:
        if not announced:
            set_status("Wi-Fi disconnected, reconnecting...")
            announced = True
        try:
            wifi.radio.connect(ssid=WIFI_SSID, password=WIFI_PASSWORD)
        except Exception as e:
            print("Wi-Fi connect failed:", e)
            ticking_sleep(5)
    if STATIC_DNS:
        try:
            wifi.radio.ipv4_dns = ipaddress.IPv4Address(STATIC_DNS)
        except Exception as e:
            print("Could not set static DNS:", e)


def reset_wifi():
    """Full radio reset; recovers from DNS dying while still 'connected'."""
    print("Resetting Wi-Fi radio")
    try:
        wifi.radio.enabled = False
        time.sleep(1)
        wifi.radio.enabled = True
    except Exception as e:
        print("Radio reset failed:", e)
    connect_wifi()


def fetch_json(url):
    """GET a URL and return the parsed JSON, or None if all retries fail."""
    for attempt in range(REQUEST_RETRIES):
        gc.collect()
        try:
            with session.get(url, timeout=REQUEST_TIMEOUT) as response:
                return response.json()
        except Exception as e:
            print(
                f"Request failed ({e}), attempt {attempt + 1}/{REQUEST_RETRIES}: {url}"
            )
            if attempt == 0:
                connect_wifi()  # cheap: no-op unless the connection dropped
            else:
                reset_wifi()
            ticking_sleep(1)
    return None


def sync_clock():
    """Set the RTC from NTP. Returns True on success."""
    for attempt in range(5):
        try:
            rtc.RTC().datetime = ntp.datetime
            return True
        except Exception as e:
            print(f"NTP sync failed ({e}), attempt {attempt + 1}/5")
            ticking_sleep(2)
            connect_wifi()
    return False


# --- Weather ------------------------------------------------------------------


def get_weather():
    """Fetch weather values. Returns (values dict or None, problem string).

    Also updates the global UTC offset, since both sources report it.
    """
    global timezone

    data = fetch_json(OPEN_METEO_URL)
    if data is not None:
        try:
            daily = data["daily"]
            values = {
                "current_today": round(data["current"]["temperature_2m"]),
                "high_today": round(daily["temperature_2m_max"][0]),
                "chance_of_rain": round(daily["precipitation_probability_max"][0]),
                "uv_index": round(daily["uv_index_max"][0]),
            }
            timezone = int(data["utc_offset_seconds"])
            return values, ""
        except (KeyError, IndexError, TypeError) as e:
            print("Unexpected Open-Meteo response:", e)

    if OWM_API_KEY:
        data = fetch_json(OWM_WEATHER_URL)
        if data is not None:
            try:
                values = {
                    "current_today": round(data["main"]["temp"]),
                    "high_today": round(data["main"]["temp_max"]),
                    "chance_of_rain": None,
                    "uv_index": None,
                }
                timezone = int(data.get("timezone", timezone))
                return values, "Open-Meteo down; OWM temps only"
            except KeyError as e:
                print("Unexpected OpenWeatherMap response:", e)

    return None, "weather fetch failed"


def refresh_weather():
    """Fetch weather, update the display state, and return the next fetch time."""
    values, problem = get_weather()
    if values is not None:
        # Keep stale values for anything this fetch could not provide
        for key, val in values.items():
            if val is not None:
                weather[key] = val

    lt = time.localtime(time.time() + timezone)
    stamp = f"{lt.tm_hour:02}:{lt.tm_min:02}"
    if problem:
        set_status(f"{problem} @ {stamp}")
        return time.monotonic() + WEATHER_RETRY_INTERVAL
    set_status("")
    print("Weather updated @", stamp)
    return time.monotonic() + WEATHER_INTERVAL


# --- Setup --------------------------------------------------------------------

spi = busio.SPI(board.GP10, board.GP11, board.GP12)

sdcard = sdcardio.SDCard(spi, board.GP22)
vfs = storage.VfsFat(sdcard)
# readonly: we only ever read fonts from the card, and CircuitPython exposes
# the card as a second USB drive on the PC — only one side may have write
# access, so mounting read-only here is what makes the card writable from
# the PC.
try:
    storage.mount(vfs, "/sd", readonly=True)
except RuntimeError:
    # CircuitPython 9+ requires the mount point directory to exist on CIRCUITPY
    try:
        os.mkdir("/sd")
    except OSError:
        # Flash is read-only to code while USB is connected, so we can't
        # create it ourselves here
        print("Create an empty folder named 'sd' on the CIRCUITPY drive")
        raise
    storage.mount(vfs, "/sd", readonly=True)

lcd = ILI9488(spi, board.GP9, board.GP15, board.GP8)
lcd.rect(0, 0, 480, 320, BLACK)

set_status("connecting to Wi-Fi...")
connect_wifi()

pool = socketpool.SocketPool(wifi.radio)
session = adafruit_requests.Session(pool, ssl.create_default_context())
ntp = adafruit_ntp.NTP(pool, server="pool.ntp.org", tz_offset=0)

set_status("syncing clock (NTP)...")
while not sync_clock():
    set_status("NTP sync failed, retrying...")
    ticking_sleep(30)
clock_synced = True
set_status("")

next_weather_sync = time.monotonic()  # fetch on the first loop pass
next_ntp_sync = time.monotonic() + NTP_INTERVAL

# --- Main loop ------------------------------------------------------------------

while True:
    try:
        # Draw first so the clock appears before the initial weather fetch
        draw_clock()
        draw_weather()

        now = time.monotonic()
        if now >= next_weather_sync:
            next_weather_sync = refresh_weather()
            gc.collect()

        if now >= next_ntp_sync:
            if not sync_clock():
                set_status("NTP re-sync failed")
            next_ntp_sync = now + NTP_INTERVAL

        time.sleep(0.1)
    except Exception as e:
        # Network problems are handled inside the fetch functions, so anything
        # that lands here is unexpected; reboot rather than freeze.
        print("Unexpected error, reloading:", e)
        time.sleep(5)
        supervisor.reload()
